//! Generates the `example_tests.rs` file that drives the end-to-end examples suite.
//!
//! The corpus of Kit fixtures is kept in `examples/` at the workspace root. Rather than hand-writing a
//! `#[test]` function for every fixture (which is how this suite originally worked, and which let
//! fixtures silently drift out of coverage), this build script scans the `examples/` directory and
//! emits one `#[test]` function per fixture. Tests are discovered from the *files on disk*, so:
//!
//! - a fixture is a `*.kit` file with a sibling `*.kit.expected` file (the expected stdout) → "run
//!   and compare", or
//! - a `*.kit` file under `examples/negative/` (no `.expected`) -> must fail to compile, or
//! - a `*.kit` file under `examples/showcase/` or `examples/modules/**` that is a non-entry-point
//!   dependency -> not a test (or not feasibly testable).
//!
//! Optional stdin is read from a `<name>.kit.stdin` sidecar file.
//!
//! Generated test names are derived from the fixture's file stem (using the enclosing category
//! directory only if that would collide).
//!
//! Because each fixture becomes its own `#[test]`, `cargo test` can filter per category:
//! ```rust,norun
//! cargo test -p kitc --test examples -- struct
//! ```
//! runs every struct fixture, and each one reports pass/fail individually.

use std::{
    collections::HashSet,
    env,
    fmt::Write as _,
    fs,
    path::{Path, PathBuf},
};

/// The kinds of fixtures a `*.kit` file can become, in priority order.
#[derive(Clone, Copy, PartialEq)]
enum Kind {
    RunCompare,
    CompileFail,
    Skip,
}

fn main() {
    let manifest_dir =
        PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));

    let examples_dir = manifest_dir
        .parent()
        .expect("kitc crate should live directly under the workspace root")
        .join("examples");

    // Rebuild whenever the corpus changes so new/renamed fixtures are picked up.
    println!("cargo:rerun-if-changed={}", examples_dir.display());

    let mut kit_files = Vec::new();
    collect_kit_files(&examples_dir, &mut kit_files);
    kit_files.sort();

    let mut generated = String::from("// @generated by build.rs -- do not edit.\n\n");
    let mut used_names: HashSet<String> = HashSet::new();
    let mut warnings = Vec::new();

    for path in &kit_files {
        let rel = path
            .strip_prefix(&examples_dir)
            .expect("under examples dir");
        let rel_str = rel.to_string_lossy().replace('\\', "/");
        let stem = path
            .file_stem()
            .and_then(|s| s.to_str())
            .expect("utf-8 file stem")
            .to_string();

        watch_file(path);
        let expected = path.with_extension("kit.expected");
        watch_file(&expected);
        let stdin_sidecar = path.with_extension("kit.stdin");
        watch_file(&stdin_sidecar);

        let kind = if expected.exists() {
            Kind::RunCompare
        } else if rel_str.starts_with("negative/") {
            Kind::CompileFail
        } else {
            Kind::Skip // showcase, or a dependency module under modules/**, or an oversight
        };

        match kind {
            Kind::RunCompare => {
                let stdin = if stdin_sidecar.exists() {
                    let data = fs::read(&stdin_sidecar).expect("read stdin sidecar");
                    let s = String::from_utf8(data).expect("stdin sidecar is utf-8");
                    format!("Some({:?})", s)
                } else {
                    "None".to_string()
                };
                // Only top-level module examples need a source path for import resolution.
                let source_path = if rel_str.starts_with("modules/") {
                    format!("Some({:?})", "examples/modules")
                } else {
                    "None".to_string()
                };
                emit_test(
                    &mut generated,
                    &mut used_names,
                    path,
                    &rel_str,
                    &stem,
                    &format!(
                        "run_fixture({:?}, {}, FixtureKind::RunCompare, {})",
                        rel_str, stdin, source_path
                    ),
                );
            }
            Kind::CompileFail => {
                emit_test(
                    &mut generated,
                    &mut used_names,
                    path,
                    &rel_str,
                    &stem,
                    &format!(
                        "run_fixture({:?}, None, FixtureKind::CompileFail, None)",
                        rel_str
                    ),
                );
            }
            Kind::Skip if rel_str.starts_with("showcase/") || rel_str.starts_with("modules/") => {
                // Intentionally not a test: showcase demos need external libs; modules/** without
                // a sibling `.expected` are dependency modules loaded by entry-point mains.
            }
            Kind::Skip => {
                warnings.push(format!(
                    "kitc: `{}` has no `.kit.expected` and is not under `negative/`, `showcase/`, or `modules/` -- it is not covered by the examples suite",
                    rel_str
                ));
            }
        }
    }

    for warning in &warnings {
        println!("cargo:warning={warning}");
    }

    let out_path = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR")).join("example_tests.rs");
    fs::write(&out_path, generated).expect("write generated tests");
}

/// Emits a `#[test]` function, deriving a unique Rust identifier from the fixture name.
fn emit_test(
    generated: &mut String,
    used_names: &mut HashSet<String>,
    path: &Path,
    rel_str: &str,
    stem: &str,
    body: &str,
) {
    let mut name = sanitize_ident(stem);
    if !used_names.insert(name.clone()) {
        let category = match path.parent().and_then(Path::file_name) {
            Some(p) => p.to_string_lossy(),
            None => "".into(),
        };
        name = sanitize_ident(&format!("{category}_{stem}"));
        if !used_names.insert(name.clone()) {
            let flat = rel_str.replace('/', "_");
            name = format!("e_{}", sanitize_ident(&flat));
        }
    }

    let _ = write!(
        generated,
        "#[test]\nfn {name}() -> Result<(), Box<dyn std::error::Error>> {{\n    {body}\n}}\n\n"
    );
}

fn sanitize_ident(s: &str) -> String {
    let mut out: String = s
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == '_' {
                c
            } else {
                '_'
            }
        })
        .collect();
    if out.is_empty() {
        out.push_str("e_");
    }
    let first = out.chars().next().expect("non-empty");
    if !first.is_ascii_alphabetic() {
        out.insert_str(0, "e_");
    }
    out
}

fn watch_file(path: &Path) {
    if path.exists() {
        println!("cargo:rerun-if-changed={}", path.display());
    }
}

fn collect_kit_files(dir: &Path, out: &mut Vec<PathBuf>) {
    for entry in fs::read_dir(dir).expect("read dir") {
        let entry = entry.expect("dir entry");
        let path = entry.path();
        if path.is_dir() {
            collect_kit_files(&path, out);
        } else if path.extension().and_then(|e| e.to_str()) == Some("kit") {
            out.push(path);
        }
    }
}
